### ISSUE TITLE
Catch duplicate user error

### ISSUE THREAD

**Issue by aaspring** [um-cseg/chez-betty#164]

**Comment by ewust** [comment]
Is this because the POS linux-distro can't verify SHA-256 signed certs?

**Comment by zakird** [comment]
That changed several days ago, so I don't think that's it.

**Comment by aaspring** [comment]
Returning to the website fixes the problem. The "Internal Server Error" was on a ~~~/purchase/XXXXXXXXXX URL. Don't know if that transaction was processed correctly. (don't have the number)

**Comment by ppannuto** [comment]
From the logs, it looks like this is what threw the issue:

```
2015-01-17 11:43:46 EST ERROR:  duplicate key value violates unique constraint "users_umid_key"
2015-01-17 11:43:46 EST DETAIL:  Key (umid)=(82665510) already exists.
2015-01-17 11:43:46 EST STATEMENT:  INSERT INTO users (id, uniqname, umid, password, salt, enabled, role) VALUES (412, 'soloway', '82665510', NULL, NULL, true, 'user')
```

Why it tried to re-insert a user is an interesting question. We should handle this error gracefully however.

**Comment by zakird** [comment]
http://pyramid-tutorials.readthedocs.org/en/latest/getting_started/11-sqlalchemy/ 

really terrible transaction management in pyramid is my guest as to why this is happening

**Comment by ppannuto** [comment]
This is still a problem:

```
[Sat Apr 04 15:07:15.496475 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] mod_wsgi (pid=9886): Exception occurred processing WSGI script '/var/chezbetty/conf/pyramid.wsgi'.
[Sat Apr 04 15:07:15.496596 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] Traceback (most recent call last):
[Sat Apr 04 15:07:15.496683 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 951, in _execute_context
[Sat Apr 04 15:07:15.496701 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     context)
[Sat Apr 04 15:07:15.496757 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/engine/default.py", line 436, in do_execute
[Sat Apr 04 15:07:15.496773 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     cursor.execute(statement, parameters)
[Sat Apr 04 15:07:15.496812 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] psycopg2.IntegrityError: duplicate key value violates unique constraint "users_umid_key"
[Sat Apr 04 15:07:15.496826 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] DETAIL:  Key (umid)=(26588416) already exists.
[Sat Apr 04 15:07:15.496833 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] 
[Sat Apr 04 15:07:15.496857 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] 
[Sat Apr 04 15:07:15.496868 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] The above exception was the direct cause of the following exception:
[Sat Apr 04 15:07:15.496875 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] 
[Sat Apr 04 15:07:15.496896 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] Traceback (most recent call last):
[Sat Apr 04 15:07:15.496963 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/router.py", line 242, in __call__
[Sat Apr 04 15:07:15.496979 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     response = self.invoke_subrequest(request, use_tweens=True)
[Sat Apr 04 15:07:15.497032 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/router.py", line 217, in invoke_subrequest
[Sat Apr 04 15:07:15.497047 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     response = handle_request(request)
[Sat Apr 04 15:07:15.497097 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/tweens.py", line 21, in excview_tween
[Sat Apr 04 15:07:15.497113 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     response = handler(request)
[Sat Apr 04 15:07:15.497164 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 82, in tm_tween
[Sat Apr 04 15:07:15.497179 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     reraise(*exc_info)
[Sat Apr 04 15:07:15.497231 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid_tm-0.7-py3.4.egg/pyramid_tm/compat.py", line 13, in reraise
[Sat Apr 04 15:07:15.497262 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     raise value
[Sat Apr 04 15:07:15.497318 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 63, in tm_tween
[Sat Apr 04 15:07:15.497333 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     response = handler(request)
[Sat Apr 04 15:07:15.497382 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/router.py", line 163, in handle_request
[Sat Apr 04 15:07:15.497397 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     response = view_callable(context, request)
[Sat Apr 04 15:07:15.497448 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/config/views.py", line 245, in _secured_view
[Sat Apr 04 15:07:15.497462 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     return view(context, request)
[Sat Apr 04 15:07:15.497512 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/config/views.py", line 355, in rendered_view
[Sat Apr 04 15:07:15.497526 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     result = view(context, request)
[Sat Apr 04 15:07:15.497575 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/config/views.py", line 501, in _requestonly_view
[Sat Apr 04 15:07:15.497589 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     response = view(request)
[Sat Apr 04 15:07:15.497641 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/chezbetty-1.4.1.post145.dev37909289-py3.4.egg/chezbetty/views.py", line 114, in purchase
[Sat Apr 04 15:07:15.497656 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     user = User.from_umid(request.matchdict['umid'])
[Sat Apr 04 15:07:15.497706 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/transaction-1.4.3-py3.4.egg/transaction/_manager.py", line 120, in __exit__
[Sat Apr 04 15:07:15.497720 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     self.commit()
[Sat Apr 04 15:07:15.497769 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/transaction-1.4.3-py3.4.egg/transaction/_manager.py", line 111, in commit
[Sat Apr 04 15:07:15.497784 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     return self.get().commit()
[Sat Apr 04 15:07:15.497833 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 280, in commit
[Sat Apr 04 15:07:15.497848 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     reraise(t, v, tb)
[Sat Apr 04 15:07:15.497897 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/transaction-1.4.3-py3.4.egg/transaction/_compat.py", line 55, in reraise
[Sat Apr 04 15:07:15.497912 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     raise value
[Sat Apr 04 15:07:15.497961 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 271, in commit
[Sat Apr 04 15:07:15.497987 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     self._commitResources()
[Sat Apr 04 15:07:15.498042 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 417, in _commitResources
[Sat Apr 04 15:07:15.498056 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     reraise(t, v, tb)
[Sat Apr 04 15:07:15.498106 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/transaction-1.4.3-py3.4.egg/transaction/_compat.py", line 55, in reraise
[Sat Apr 04 15:07:15.498120 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     raise value
[Sat Apr 04 15:07:15.498168 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/transaction-1.4.3-py3.4.egg/transaction/_transaction.py", line 389, in _commitResources
[Sat Apr 04 15:07:15.498182 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     rm.tpc_begin(self)
[Sat Apr 04 15:07:15.498232 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/zope.sqlalchemy-0.7.5-py3.4.egg/zope/sqlalchemy/datamanager.py", line 90, in tpc_begin
[Sat Apr 04 15:07:15.498246 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     self.session.flush()
[Sat Apr 04 15:07:15.498295 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1919, in flush
[Sat Apr 04 15:07:15.498310 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     self._flush(objects)
[Sat Apr 04 15:07:15.498358 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2037, in _flush
[Sat Apr 04 15:07:15.498373 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     transaction.rollback(_capture_exception=True)
[Sat Apr 04 15:07:15.498423 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
[Sat Apr 04 15:07:15.498438 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     compat.reraise(exc_type, exc_value, exc_tb)
[Sat Apr 04 15:07:15.498488 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/util/compat.py", line 182, in reraise
[Sat Apr 04 15:07:15.498503 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     raise value
[Sat Apr 04 15:07:15.498552 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2001, in _flush
[Sat Apr 04 15:07:15.498566 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     flush_context.execute()
[Sat Apr 04 15:07:15.498615 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 372, in execute
[Sat Apr 04 15:07:15.498629 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     rec.execute(self)
[Sat Apr 04 15:07:15.498678 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 526, in execute
[Sat Apr 04 15:07:15.498705 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     uow
[Sat Apr 04 15:07:15.498761 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 65, in save_obj
[Sat Apr 04 15:07:15.498776 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     mapper, table, insert)
[Sat Apr 04 15:07:15.498827 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 570, in _emit_insert_statements
[Sat Apr 04 15:07:15.498842 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     execute(statement, multiparams)
[Sat Apr 04 15:07:15.498891 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 729, in execute
[Sat Apr 04 15:07:15.498906 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     return meth(self, multiparams, params)
[Sat Apr 04 15:07:15.498958 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
[Sat Apr 04 15:07:15.498973 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     return connection._execute_clauseelement(self, multiparams, params)
[Sat Apr 04 15:07:15.499022 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
[Sat Apr 04 15:07:15.499037 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     compiled_sql, distilled_params
[Sat Apr 04 15:07:15.499086 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 958, in _execute_context
[Sat Apr 04 15:07:15.499100 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     context)
[Sat Apr 04 15:07:15.499148 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
[Sat Apr 04 15:07:15.499163 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     exc_info
[Sat Apr 04 15:07:15.499214 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/util/compat.py", line 188, in raise_from_cause
[Sat Apr 04 15:07:15.499229 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
[Sat Apr 04 15:07:15.499278 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/util/compat.py", line 181, in reraise
[Sat Apr 04 15:07:15.499293 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     raise value.with_traceback(tb)
[Sat Apr 04 15:07:15.499342 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 951, in _execute_context
[Sat Apr 04 15:07:15.499368 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     context)
[Sat Apr 04 15:07:15.499422 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]   File "/var/chezbetty/lib/python3.4/site-packages/SQLAlchemy-0.9.7-py3.4-linux-x86_64.egg/sqlalchemy/engine/default.py", line 436, in do_execute
[Sat Apr 04 15:07:15.499438 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]     cursor.execute(statement, parameters)
[Sat Apr 04 15:07:15.499534 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] sqlalchemy.exc.IntegrityError: (IntegrityError) duplicate key value violates unique constraint "users_umid_key"
[Sat Apr 04 15:07:15.499553 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384] DETAIL:  Key (umid)=(26588416) already exists.
[Sat Apr 04 15:07:15.499561 2015] [:error] [pid 9886:tid 139667114567424] [remote 141.212.106.106:18384]  'INSERT INTO users (id, uniqname, umid, password, salt, enabled, role) VALUES (%(id)s, %(uniqname)s, %(umid)s, %(password)s, %(salt)s, %(enabled)s, %(role)s)' {'id': 601, 'password': None, 'umid': 'SANITIZED', 'salt': None, 'uniqname': 'jtesmer', 'role': 'user', 'enabled': True}
```

**Comment by bradjc** [comment]
I don't think humans were meant to fix this error.
