### ISSUE TITLE
Look into user view with no transaction history

### ISSUE THREAD

**Issue by ppannuto** [um-cseg/chez-betty#211]
```
[Tue Nov 17 17:31:16.775267 2015] [:error] [pid 888:tid 140258871187200] An unknown error occurred:
[Tue Nov 17 17:31:16.775341 2015] [:error] [pid 888:tid 140258871187200] Traceback (most recent call last):
[Tue Nov 17 17:31:16.775415 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/tweens.py", line 21, in excview_tween
[Tue Nov 17 17:31:16.775427 2015] [:error] [pid 888:tid 140258871187200]     response = handler(request)
[Tue Nov 17 17:31:16.775470 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 82, in tm_tween
[Tue Nov 17 17:31:16.775480 2015] [:error] [pid 888:tid 140258871187200]     reraise(*exc_info)
[Tue Nov 17 17:31:16.775518 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid_tm-0.7-py3.4.egg/pyramid_tm/compat.py", line 13, in reraise
[Tue Nov 17 17:31:16.775528 2015] [:error] [pid 888:tid 140258871187200]     raise value
[Tue Nov 17 17:31:16.775564 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 63, in tm_tween
[Tue Nov 17 17:31:16.775574 2015] [:error] [pid 888:tid 140258871187200]     response = handler(request)
[Tue Nov 17 17:31:16.775613 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/router.py", line 163, in handle_request
[Tue Nov 17 17:31:16.775623 2015] [:error] [pid 888:tid 140258871187200]     response = view_callable(context, request)
[Tue Nov 17 17:31:16.775662 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/config/views.py", line 245, in _secured_view
[Tue Nov 17 17:31:16.775672 2015] [:error] [pid 888:tid 140258871187200]     return view(context, request)
[Tue Nov 17 17:31:16.775709 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/config/views.py", line 377, in rendered_view
[Tue Nov 17 17:31:16.775719 2015] [:error] [pid 888:tid 140258871187200]     context)
[Tue Nov 17 17:31:16.775757 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/renderers.py", line 418, in render_view
[Tue Nov 17 17:31:16.775768 2015] [:error] [pid 888:tid 140258871187200]     return self.render_to_response(response, system, request=request)
[Tue Nov 17 17:31:16.775804 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/renderers.py", line 441, in render_to_response
[Tue Nov 17 17:31:16.775814 2015] [:error] [pid 888:tid 140258871187200]     result = self.render(value, system_values, request=request)
[Tue Nov 17 17:31:16.775851 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid-1.5.1-py3.4.egg/pyramid/renderers.py", line 437, in render
[Tue Nov 17 17:31:16.775889 2015] [:error] [pid 888:tid 140258871187200]     result = renderer(value, system_values)
[Tue Nov 17 17:31:16.775933 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/pyramid_jinja2-2.3.3-py3.4.egg/pyramid_jinja2/__init__.py", line 265, in __call__
[Tue Nov 17 17:31:16.775943 2015] [:error] [pid 888:tid 140258871187200]     return template.render(system)
[Tue Nov 17 17:31:16.775982 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/Jinja2-2.7.3-py3.4.egg/jinja2/environment.py", line 969, in render
[Tue Nov 17 17:31:16.775992 2015] [:error] [pid 888:tid 140258871187200]     return self.environment.handle_exception(exc_info, True)
[Tue Nov 17 17:31:16.776028 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/Jinja2-2.7.3-py3.4.egg/jinja2/environment.py", line 742, in handle_exception
[Tue Nov 17 17:31:16.776038 2015] [:error] [pid 888:tid 140258871187200]     reraise(exc_type, exc_value, tb)
[Tue Nov 17 17:31:16.776075 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/Jinja2-2.7.3-py3.4.egg/jinja2/_compat.py", line 36, in reraise
[Tue Nov 17 17:31:16.776085 2015] [:error] [pid 888:tid 140258871187200]     raise value.with_traceback(tb)
[Tue Nov 17 17:31:16.776128 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/chezbetty-1.4.1.post282.dev229118470-py3.4.egg/chezbetty/templates/terminal/user.jinja2", line 2, in <module>
[Tue Nov 17 17:31:16.776138 2015] [:error] [pid 888:tid 140258871187200]     {% set active_page = 'account' %}
[Tue Nov 17 17:31:16.776177 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/chezbetty-1.4.1.post282.dev229118470-py3.4.egg/chezbetty/templates/terminal/base.jinja2", line 110, in <module>
[Tue Nov 17 17:31:16.776187 2015] [:error] [pid 888:tid 140258871187200]     {% block content %}{% endblock %}
[Tue Nov 17 17:31:16.776225 2015] [:error] [pid 888:tid 140258871187200]   File "/var/chezbetty/lib/python3.4/site-packages/chezbetty-1.4.1.post282.dev229118470-py3.4.egg/chezbetty/templates/terminal/user.jinja2", line 129, in <module>
[Tue Nov 17 17:31:16.776235 2015] [:error] [pid 888:tid 140258871187200]     {% elif transactions|length < transactions_count %}
[Tue Nov 17 17:31:16.776266 2015] [:error] [pid 888:tid 140258871187200] TypeError: unorderable types: int() < NoneType()
```

**Comment by ppannuto** [comment]
Poked around a bit with a new user account and couldn't repro this. Who knows.
